name: binary-signed-ghat-malicious
on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      id-token: write
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: The malicious step
        run: |
          echo "// This is a malicious update" >> main.go
      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: '1.21'
      - name: Run Go build
        run: |
          go build -v -o demo-go-binary ./...
      - name: Sign artifact
        uses: github-early-access/generate-build-provenance@ba7adadb35401941c27eb9c779df6e0aa8f44a6f # main
        with:
          subject-path: '${{ github.workspace }}/demo-go-binary'
      - name: Upload artifact
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: demo-go-binary
          path: demo-go-binary
